version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor: 
      name: android/android-machine
      tag: 2023.09.1
    steps:
      - checkout
      - android/change-java-version:
          java-version: 17
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Code Coverage
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: app/build/reports
          destination: reports
      # Add steps for code style analysis, vulnerability scanning, etc.
